import uuid
from decimal import Decimal

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.logger import get_logger, log_operation
from app.core.redis import redis_client
from app.db.models.product import Product
from app.db.models.product_shop import ProductShop
from app.db.models.shop import Shop
from app.db.models.user import User
from app.db.repositories.exchange_rate_repo import ExchangeRateRepo
from app.services.currency_service import CurrencyService
from app.services.db_service import db_service
from app.services.shop_adapters.base import ShopProduct
from app.services.shop_adapters.dummyjson import DummyJsonAdapter
from app.services.shop_adapters.fakestore import FakeStoreAdapter

logger = get_logger(__name__)

DUMMYJSON_KEY = "dummyjson"
FAKESTORE_KEY = "fakestore"

# Fixed UUID for the demo user — matches the JWT generated by scripts/generate_token.py
DEMO_USER_ID = uuid.UUID("10000000-0000-0000-0000-000000000001")


async def seed_shops(db: AsyncSession) -> dict[str, int]:
    """Create shop records. Returns {adapter_key: shop_id}."""
    with log_operation(logger, "seed_shops"):
        shops = [
            Shop(name="DummyJSON", base_url=settings.dummyjson_url, adapter_key=DUMMYJSON_KEY, is_active=True),
            Shop(name="FakeStore", base_url=settings.fakestore_url, adapter_key=FAKESTORE_KEY, is_active=True),
        ]
        for shop in shops:
            db.add(shop)

        await db.flush()  # get the auto-increment id from the DB
        shop_ids = {s.adapter_key: s.id for s in shops}
        await db.commit()

        logger.info(f"Seeded {len(shops)} shops: {list(shop_ids.keys())}")
        return shop_ids


def _map_by_nearest_price(
    dummy_products: list[ShopProduct],
    fakestore_products: list[ShopProduct],
) -> dict[int, ShopProduct]:
    """Match each FakeStore product to the closest-priced DummyJSON product.

    Returns {dummy_index: fakestore_product}. Each DummyJSON product is used at
    most once (a 1:1 match), so the two shops of one logical product keep similar
    prices. Greedy by the smallest price gap — good enough for a demo seed.
    """
    mapping: dict[int, ShopProduct] = {}
    used: set[int] = set()
    for fakestore in fakestore_products:
        best_idx: int | None = None
        best_gap: Decimal | None = None
        for i, dummy in enumerate(dummy_products):
            if i in used:
                continue
            gap = abs(dummy.price_usd - fakestore.price_usd)
            if best_gap is None or gap < best_gap:
                best_idx, best_gap = i, gap
        if best_idx is None:
            break  # no DummyJSON products left to match
        used.add(best_idx)
        mapping[best_idx] = fakestore
    return mapping


async def seed_products(db: AsyncSession, shop_ids: dict[str, int]) -> None:
    """
    Load products from DummyJSON and FakeStore.

    Every DummyJSON product becomes one logical product. Each FakeStore product
    is then attached as a second shop to the DummyJSON product with the closest
    price (see _map_by_nearest_price). This keeps the cross-shop pairs plausible
    (both shops have a similar price for one product) instead of the old
    map-by-index, which paired unrelated items with very different prices.
    The other ~174 DummyJSON products stay single-shop.
    """
    dummyjson_id = shop_ids[DUMMYJSON_KEY]
    fakestore_id = shop_ids[FAKESTORE_KEY]

    with log_operation(logger, "seed_products"):
        logger.info("Fetching products from DummyJSON...")
        dummy_products = await DummyJsonAdapter(settings.dummyjson_url).fetch_products()
        logger.info(f"Fetched {len(dummy_products)} products from DummyJSON")

        logger.info("Fetching products from FakeStore...")
        fakestore_products = await FakeStoreAdapter(settings.fakestore_url).fetch_products()
        logger.info(f"Fetched {len(fakestore_products)} products from FakeStore")

        # DummyJSON product (by index) -> the logical product UUID
        product_ids: list[uuid.UUID] = []
        for dummy in dummy_products:
            # Generate the UUID here — default=uuid.uuid4 in the model runs only
            # on INSERT (flush), not when the Python object is created
            product_id = uuid.uuid4()
            product_ids.append(product_id)
            db.add(Product(
                id=product_id,
                title=dummy.title,
                description=dummy.description,
                category=dummy.category,
                description_source_shop_id=dummyjson_id,
            ))
            db.add(ProductShop(
                product_id=product_id,
                shop_id=dummyjson_id,
                external_id=dummy.external_id,
            ))

        mapped = _map_by_nearest_price(dummy_products, fakestore_products)
        for dummy_idx, fakestore in mapped.items():
            db.add(ProductShop(
                product_id=product_ids[dummy_idx],
                shop_id=fakestore_id,
                external_id=fakestore.external_id,
            ))

        await db.commit()
        logger.info(
            f"Seeded {len(dummy_products)} products | "
            f"dummyjson={len(dummy_products)} fakestore_mapped={len(mapped)}"
        )


async def seed_demo_user(db: AsyncSession) -> None:
    """Create the demo user if it doesn't exist. UUID matches scripts/generate_token.py."""
    with log_operation(logger, "seed_demo_user", user_id=DEMO_USER_ID):
        existing = await db.scalar(select(User.id).where(User.id == DEMO_USER_ID))
        if existing:
            logger.info("Demo user already exists, skipping")
            return

        db.add(User(
            id=DEMO_USER_ID,
            email="admin@pricetracker.com",
            is_active=True,
        ))
        await db.commit()
        logger.info(f"Demo user created | id={DEMO_USER_ID}")


async def run_seed_if_needed() -> None:
    """Idempotent startup seed: demo user, shops, products, today's rates.

    Runs from lifespan only in the api container (RUN_SEED_ON_STARTUP=true).
    Each step is checked on its own — safe against a partly done seed.
    External API failures do not break app startup (graceful degradation).
    """
    with log_operation(logger, "startup seed"):
        async with db_service.session() as db:
            await seed_demo_user(db)

            shops = (await db.execute(select(Shop))).scalars().all()
            if not shops:
                logger.info("No shops found — running seed_shops")
                shop_ids = await seed_shops(db)
            else:
                shop_ids = {s.adapter_key: s.id for s in shops}
                logger.info(f"Shops already exist: {list(shop_ids.keys())}")

            products_count = (
                await db.execute(select(func.count(Product.id)))
            ).scalar()
            if products_count == 0:
                logger.info("No products found — running seed_products")
                try:
                    await seed_products(db, shop_ids)
                except Exception as e:
                    logger.warning(f"Could not seed products (API unavailable?): {e}")
            else:
                logger.info(f"Products already exist ({products_count}), skipping")

            # Sync rates on every startup (idempotent upsert for today), so
            # /currencies returns fresh data without waiting for beat.
            try:
                currency_service = CurrencyService(ExchangeRateRepo(db), redis_client)
                synced = await currency_service.sync_today_rates()
                await db.commit()
                logger.info(f"Synced {synced} exchange rates for today")
            except Exception as e:
                logger.warning(f"Could not sync exchange rates (NBU unavailable?): {e}")
