import uuid

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.logger import get_logger, log_operation
from app.core.redis import redis_client
from app.db.models.product import Product
from app.db.models.product_shop import ProductShop
from app.db.models.shop import Shop
from app.db.models.user import User
from app.db.repositories.exchange_rate_repo import ExchangeRateRepo
from app.services.currency_service import CurrencyService
from app.services.db_service import db_service
from app.services.shop_adapters.dummyjson import DummyJsonAdapter
from app.services.shop_adapters.fakestore import FakeStoreAdapter

logger = get_logger(__name__)

DUMMYJSON_KEY = "dummyjson"
FAKESTORE_KEY = "fakestore"

# Fixed UUID for the demo user — matches the JWT generated by scripts/generate_token.py
DEMO_USER_ID = uuid.UUID("10000000-0000-0000-0000-000000000001")


async def seed_shops(db: AsyncSession) -> dict[str, int]:
    """Создаёт записи магазинов. Возвращает {adapter_key: shop_id}."""
    with log_operation(logger, "seed_shops"):
        shops = [
            Shop(name="DummyJSON", base_url=settings.dummyjson_url, adapter_key=DUMMYJSON_KEY, is_active=True),
            Shop(name="FakeStore", base_url=settings.fakestore_url, adapter_key=FAKESTORE_KEY, is_active=True),
        ]
        for shop in shops:
            db.add(shop)

        await db.flush()  # получаем auto-increment id от БД
        shop_ids = {s.adapter_key: s.id for s in shops}
        await db.commit()

        logger.info(f"Seeded {len(shops)} shops: {list(shop_ids.keys())}")
        return shop_ids


async def seed_products(db: AsyncSession, shop_ids: dict[str, int]) -> None:
    """
    Загружает товары из DummyJSON и FakeStore.
    Первые 20 товаров получают цены из обоих магазинов (маппинг по индексу).
    Остальные ~174 — только из DummyJSON.
    """
    dummyjson_id = shop_ids[DUMMYJSON_KEY]
    fakestore_id = shop_ids[FAKESTORE_KEY]

    with log_operation(logger, "seed_products"):
        logger.info("Fetching products from DummyJSON...")
        dummy_products = await DummyJsonAdapter(settings.dummyjson_url).fetch_products()
        logger.info(f"Fetched {len(dummy_products)} products from DummyJSON")

        logger.info("Fetching products from FakeStore...")
        fakestore_products = await FakeStoreAdapter(settings.fakestore_url).fetch_products()
        logger.info(f"Fetched {len(fakestore_products)} products from FakeStore")

        for i, dummy in enumerate(dummy_products):
            # UUID генерируем явно — default=uuid.uuid4 в модели применяется только
            # при INSERT (flush), а не при создании Python-объекта
            product_id = uuid.uuid4()
            product = Product(
                id=product_id,
                title=dummy.title,
                description=dummy.description,
                category=dummy.category,
                description_source_shop_id=dummyjson_id,
            )
            db.add(product)

            db.add(ProductShop(
                product_id=product_id,
                shop_id=dummyjson_id,
                external_id=dummy.external_id,
            ))

            if i < len(fakestore_products):
                db.add(ProductShop(
                    product_id=product_id,
                    shop_id=fakestore_id,
                    external_id=fakestore_products[i].external_id,
                ))

        await db.commit()
        logger.info(
            f"Seeded {len(dummy_products)} products | "
            f"dummyjson={len(dummy_products)} fakestore_mapped={min(len(dummy_products), len(fakestore_products))}"
        )


async def seed_demo_user(db: AsyncSession) -> None:
    """Create the demo user if it doesn't exist. UUID matches scripts/generate_token.py."""
    with log_operation(logger, "seed_demo_user", user_id=DEMO_USER_ID):
        existing = await db.scalar(select(User.id).where(User.id == DEMO_USER_ID))
        if existing:
            logger.info("Demo user already exists, skipping")
            return

        db.add(User(
            id=DEMO_USER_ID,
            email="admin@pricetracker.com",
            is_active=True,
        ))
        await db.commit()
        logger.info(f"Demo user created | id={DEMO_USER_ID}")


async def run_seed_if_needed() -> None:
    """Идемпотентный стартовый seed: demo-user, магазины, товары, курсы на сегодня.

    Запускается из lifespan только в контейнере api (RUN_SEED_ON_STARTUP=true).
    Каждый шаг проверяется независимо — устойчивость к частично выполненному seed.
    Сбои внешних API не валят старт приложения (graceful degradation).
    """
    with log_operation(logger, "startup seed"):
        async with db_service.session() as db:
            await seed_demo_user(db)

            shops = (await db.execute(select(Shop))).scalars().all()
            if not shops:
                logger.info("No shops found — running seed_shops")
                shop_ids = await seed_shops(db)
            else:
                shop_ids = {s.adapter_key: s.id for s in shops}
                logger.info(f"Shops already exist: {list(shop_ids.keys())}")

            products_count = (
                await db.execute(select(func.count(Product.id)))
            ).scalar()
            if products_count == 0:
                logger.info("No products found — running seed_products")
                try:
                    await seed_products(db, shop_ids)
                except Exception as e:
                    logger.warning(f"Could not seed products (API unavailable?): {e}")
            else:
                logger.info(f"Products already exist ({products_count}), skipping")

            # Курсы синхронизируем при каждом старте (идемпотентный upsert на сегодня),
            # чтобы /currencies отдавал актуальное, не дожидаясь beat.
            try:
                currency_service = CurrencyService(ExchangeRateRepo(db), redis_client)
                synced = await currency_service.sync_today_rates()
                await db.commit()
                logger.info(f"Synced {synced} exchange rates for today")
            except Exception as e:
                logger.warning(f"Could not sync exchange rates (NBU unavailable?): {e}")
