"""initial

Revision ID: 11f8cd6cb440
Revises: 
Create Date: 2026-06-23 19:50:06.710219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f8cd6cb440'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=False),
    sa.Column('rate_uah_per_unit', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_code', 'date')
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('adapter_key', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adapter_key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('description_source_shop_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['description_source_shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('threshold_price_usd', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_alert_active_product', 'price_alerts', ['is_active', 'product_id'], unique=False)
    op.create_table('product_shops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'shop_id')
    )
    op.create_index('ix_product_shop_product_id', 'product_shops', ['product_id'], unique=False)
    op.create_table('user_products',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('product_shop_id', sa.Integer(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_shop_id'], ['product_shops.id'], ),
    sa.PrimaryKeyConstraint('id', 'recorded_at'),
    postgresql_partition_by='RANGE (recorded_at)'
    )
    op.create_index('ix_price_history_lookup', 'price_history', ['product_shop_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###

    # Создаём начальные партиции price_history.
    # Celery-задача create_monthly_partition_task создаёт следующие партиции 1-го числа каждого месяца.
    op.execute("""
        CREATE TABLE price_history_2026_06
            PARTITION OF price_history
            FOR VALUES FROM ('2026-06-01') TO ('2026-07-01')
    """)
    op.execute("""
        CREATE TABLE price_history_2026_07
            PARTITION OF price_history
            FOR VALUES FROM ('2026-07-01') TO ('2026-08-01')
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history_2026_07')
    op.drop_table('price_history_2026_06')
    op.drop_index('ix_price_history_lookup', table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('user_products')
    op.drop_index('ix_product_shop_product_id', table_name='product_shops')
    op.drop_table('product_shops')
    op.drop_index('ix_price_alert_active_product', table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('shops')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
